---
- name: Restart JBoss
  service: name=jboss-as state=restarted
  environment:
      LANG: "en_US.UTF-8"

- name: Restart standalone JBoss
  service: name=jboss-as-{{node_name}} state=restarted
  environment:
      LANG: "en_US.UTF-8"

