---
- hosts: node01
  become: yes
  gather_facts: no

  vars:
    distr_name: jboss-eap-6.4.0.zip
    jboss_dir: /u01/jboss

  tasks:
  - name: PINGING
    ping:

  - debug:
      msg: "JBOSS INSTALL"

  - name: upload JBoss EAP distr
    copy: src=jboss_install/files/jboss_eap/6.4/{{ distr_name }} dest=/tmp

  - name: install requirements
    yum: name={{ item }} state=installed
    loop:
       - unzip
       - java-1.8.0-openjdk-devel.x86_64

  - name: create jboss group
    group: name=jboss state=present system=yes

  - name: create jboss user
    user: name=jboss group=jboss system=yes

  - name: create jboss dir
    file: state=directory dest={{ jboss_dir }} owner=jboss group=jboss
  
  - name: unzip JBoss EAP distr
    unarchive: copy=no src=/tmp/{{ distr_name }} dest={{ jboss_dir }}

  - name: add  jboss user
    command: "{{ jboss_dir }}/jboss-eap-6.4/bin/add-user.sh -u MyAdmin -p password1@ -s"

  - name: Start JBoss EAP
    command: "{{jboss_dir}}/jboss-eap-6.4/bin/standalone.sh -Djboss.node.name=node01 -Djboss.server.base.dir={{ jboss_dir }}/jboss-eap-6.4/standalone -b 10.32.101.199 -bmanagement 10.32.101.199"
