---
#*********************************************************************
- name: upload jboss files
  copy: src={{item}} dest=/tmp
  loop:
    - "{{files}}/jboss_eap/6.4/jboss-eap-6.4.0.zip"
    - "{{files}}/activemq/6.3/activemq-rar-6.3.0.rar"
    - "{{files}}/jboss_eap/6.4/patches/jboss-eap-6.4.9-patch.zip"
    - "{{files}}/jboss_eap/6.4/patches/jboss-eap-6.4.19-patch.zip"
    - "{{files}}/jboss_eap/6.4/patches/jboss-eap-6.4.20-patch.zip"
#*********************************************************************



- name: create jboss system group
  group: name=jboss state=present system=yes

- name: create jboss system user
  user: name=jboss group=jboss system=yes

- name: create jboss dir
  file: state=directory dest={{jboss_dir}} owner=jboss group=jboss

- name: unzip jboss to jboss dir
  unarchive: copy=no src=/tmp/{{distr_name}} dest={{jboss_dir}}



- name: provide startup config
  template: src=jboss.conf.j2 dest=/etc/jboss-as/jboss-as-{{node_name}}.conf owner=root mode=0644

- name: provide init.d script domain
  template: src=jboss_init.j2 dest=/etc/init.d/jboss-as owner=root mode=0755

- name: provide init.d script domain for systemd
  template: src=jboss_init.j2 dest={{jboss_dir}}/jboss-eap-{{jboss_version}}/bin/init.d/systemd_jboss-as-domain.sh owner=root mode=0755

- name: provide systemd script
  template: src=jboss.service.j2 dest=/etc/systemd/system/jboss-as.service

- name: Reload systemd daemon
  systemd: daemon-reload=yes

- name: Add JBoss to autostart
  service: name=jboss-as enabled=yes
  when: not standalone|bool

- name: Start jboss
  service: name=jboss-as state=started
  when: not standalone|bool

- name: Waiting service
  wait_for:
    timeout: 10

# Deploy the activemq-rar-6.3.0.rar

#- name: Deploying activemq-rar-6.3.0.rar
#  ignore_errors: true
#  command: "{{jboss_dir}}/jboss-eap-{{jboss_version}}/bin/jboss-cli.sh --controller={{jboss_master_host}}:{{9999+(port_offset|int)}} -c --commands='deploy /tmp/activemq-rar-6.3.0.rar'"
#  environment:
#    JAVA_HOME: "/usr/"

