Vagrant.configure("2") do |config|
  config.vm.define "node01" do |node01|
    node01.vm.box = "centos7-mini"
	node01.vm.hostname = "node01"
	
	node01.vm.provider "virtualbox" do |vb|
	  # vagrant-disksize plugin feature
	  node01.vagrant.plugins = ['vagrant-disksize']
	  node01.disksize.size = '10GB'
	  vb.name = "node01"
	  vb.memory = 1024
	  vb.cpus = 1
	end
	
	node01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "ansible-net"
	node01.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller #2"
	# additional SSH 
	node01.vm.network "forwarded_port", protocol: "tcp", host_ip: "192.168.50.5",  host: 10122, guest_ip: "192.168.50.10", guest: 22
	# JBOSS
	node01.vm.network "forwarded_port", guest: 9990, host: 11090
	node01.vm.network "forwarded_port", guest: 9999, host: 11099
	node01.vm.network "forwarded_port", guest: 8080, host: 11880
	# HTTP/HTTPS
	node01.vm.network "forwarded_port", guest: 80, host: 11080
	node01.vm.network "forwarded_port", guest: 443, host: 11043
  end
  
end