---
  - name: PINGING
    ping:

#  - debug:
#      msg: "JBOSS INSTALL"

#  - name: upload JBoss EAP distr
#    copy: src=jboss_install/files/jboss_eap/6.4/{{ distr_name }} dest=/tmp

#  - name: install requirements
#    yum: name={{ item }} state=installed
#    loop:
#       - unzip
#       - java-1.8.0-openjdk-devel.x86_64

#  - name: create jboss group
#    group: name=jboss state=present system=yes

#  - name: create jboss user
#    user: name=jboss group=jboss system=yes

#  - name: create jboss dir
#    file: state=directory dest={{ jboss_dir }} owner=jboss group=jboss

#  - name: unzip JBoss EAP distr
#    unarchive: copy=no src=/tmp/{{ distr_name }} dest={{ jboss_dir }}

#  - name: add  jboss user
#    command: "{{ jboss_dir }}/jboss-eap-6.4/bin/add-user.sh -u MyAdmin -p password1@ -s"

#  - name: Start JBoss EAP
#    command: "{{jboss_dir}}/jboss-eap-6.4/bin/standalone.sh -Djboss.node.name=node01 -Djboss.server.base.dir={{ jboss_dir }}/jboss-eap-6.4/standalone -b 10.32.101.199 -bmanagement 10.32.101.199"

  - name: create config dir
    file: state=directory dest=/etc/jboss-as owner=root mode=644

  - name: provide startup config
    template: src=/home/vagrant/r_git/ansible_vagrant_jboss/jboss_install/template/jboss_standalone.conf.j2 dest=/etc/jboss-as/jboss-as.conf owner=root mode=644

  - name: provide init.d script standalone
    template: src=jboss_install/template/jboss_init_standalone.j2 dest=/etc/init.d/jboss-as owner=root mode=644
