---
files: roles/jboss_install/files
distr_name: jboss-eap-6.4
node_name: "{{ansible_hostname}}"
jboss_dir: "/opt/{{node_name}}"
port_offset: 0
jboss_version: "6.4"
#====================================================
jboss_master: admin
jboss_master_pass: admin123!@#
jboss_masters: ["node02"]
jboss_master_host: "{{ansible_all_ipv4_addresses[0]}}"
jboss_master_port: 9999
#====================================================
jboss_slaves: ["node01"]
jboss_slave_pass: "{{node_name}}123!@#"
#====================================================
domain_controller: True
#standalone: True
#====================================================
jboss_bind: "{{ansible_all_ipv4_addresses[0]}}"
#jboss_bind: "{{ansible_default_ipv4.address}}"

