---
#----------Install require software----------
- name: Install requirements
  yum: name={{ item }} state=installed
  loop:
    - unzip
#    - java-1.8.0-openjdk-devel.x86_64

#----------Disabling -firewalld- for allow net access----------
- name: Disabling firewalld service
  systemd: name=firewalld state=stopped enabled=no

#----------Disabling -SELinux- for allow net access-----------
- name: Disabling SELinux
  lineinfile:
   path: "/etc/selinux/config"
   regexp: '^SELINUX='
   line: SELINUX=disabled

#----------Reboot nodes----------
- name: Rebooting node
  shell: sleep 5 & reboot now
  async: 1
  poll: 0

- name: Wait to node wake up
  wait_for:
    host: "{{inventory_hostname}}"
    state: started
    delay: 5
    timeout: 30
  delegate_to: 127.0.0.1

#----------Deliver information about local own repo----------
- name: Deliver local repo info
  template: src=local.repo dest=/etc/yum.repos.d/local.repo mode=0755
