---
- name: deploy artifact domain
  ignore_errors: true
  command: "{{jboss_dir}}/jboss-eap-{{jboss_version}}/bin/jboss-cli.sh --controller=localhost:{{9999+(port_offset|default(0))}} -c --command='deploy /tmp/{{item.dest_name}} --server-groups={{item.dest_server_group}}'"
  with_items: "{{deployments}}"


