Vagrant.configure("2") do |config|
    config.vm.box = "centos7-mini"
    config.vm.hostname = "node01"
    config.vm.network :public_network, ip: ""
    config.vm.provision "shell",
      run: "always",
      inline: "route -A inet6 add default gw 192.168.88.1"

    config.vm.provider :virtualbox do |vb|
      vb.customize [
          "modifyvm", :id,
          "--name", "node01",
          "--cpuexecutioncap", "50",
          "--memory", "512",
        ]
  end
end

