nodes = [
  { :hostname => 'node01', :box => 'centos7-mini' },
  { :hostname => 'node02', :box => 'centos7-mini' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :public_network, ip: ""
      nodeconfig.vm.provision "shell",
        run: "always",
        inline: "sudo yum install unzip java-1.8.0-openjdk.x86_64 -y && ip a"

      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
            "modifyvm", :id,
            "--name", node[:hostname],
	    "--cpus", "1",
            "--memory", "1024",
        ]
      end
    end
  end
end

